name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ update-from-sheets ] # Permite activar el build mediante un webhook

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Herramienta actualizada a la versión 4
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Herramienta actualizada a v4 y entorno a Node 24
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # 3. Instalar dependencias
      - name: Instalar dependencias
        run: npm install

      # 4. Construir el sitio
      - name: Construir el sitio estático
        run: npm run build
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}


      - name: Sync files to Hostinger FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /public_html/
